### ISSUE TITLE
Add readme.md

### ISSUE THREAD

**Issue by aukgit** [Rashik004/Beverage-Management#34]
## Add readme.md
- use this  : https://stackedit.io/editor or http://prose.io 
- get some help from Afiqur and write a readme so that anyone can use it.

**Comment by Rashik004** [comment]
@aukgit can please give me any sample documentation of these kind of sites. I'm a bit confused about what to write.
Thanks

**Comment by aukgit** [comment]
use this : https://stackedit.io/editor or http://prose.io

**Comment by Rashik004** [comment]
@aukgit I got the editor. But I'm being confused about the content here. Like should I include algorithm used, or should I demonstrate based on used cases or should I just describe the pages I have and their functionalities?

**Comment by aukgit** [comment]
Save the edited text and save it as readme.md and add to the root of the project

**Comment by aukgit** [comment]
Great

**Comment by aukgit** [comment]
add default user name and password.

**Comment by aukgit** [comment]
If possible create first alpha release on the release tab.

**Comment by Rashik004** [comment]
@aukgit I created the first alpha release on the release tab.
