### ISSUE TITLE
Update DevMvcComponent 3.0 and remove Mailer.cs class

### ISSUE THREAD

**Issue by aukgit** [Rashik004/Beverage-Management#36]
Update DevMvcComponent 3.0 and remove Mailer.cs class

**Comment by Rashik004** [comment]
@aukgit Mailer.cs is being used in paymentcycle.cs at line 68, should I remove it??

**Comment by aukgit** [comment]
Yes,  just use Mvc.Mailer.QuickSend and it will work . No need to mark method as async.
